import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import { Box, Container, Typography, CircularProgress } from "@mui/material";
import Header from "../components/Header";
import Footer from "../components/Footer";
import useAuth from "../hooks/useAuth";

const Home: NextPage = () => {
  const [users, loading] = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box>
          <Header />
          <Container>
            {loading && <CircularProgress />}
            <Typography variant="h1">Horace Learning</Typography>
            {users?.map((user: any) => (
              <Typography key={user.id}>{user.email}</Typography>
            ))}
          </Container>
          <Footer />
        </Box>
      </main>
    </div>
  );
};

export default Home;
