#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Running pre-commit hook'

# Run Pre-commit hook
yarn run precommit || exit 1

# Run lint-staged
yarn run lint || (echo 'Code is not formatted correctly. Run "yarn format" to format the code' && exit 1)